# Path to store music
# 存放音乐的路径 (默认系统音乐路径)
music_database: ''
# Color
# 主题配色
theme:
 list_title_color: '#ffaaff'
 list_title_page_color: '#ffb747'
 list_border_color: '#ffffff'
 list_music_color: '#eee4c4'
 list_folder_color: '#eee4c4'
 list_icon_color: '#f07178'
 list_selected_color: '#c3e88d'
 search_border_color: '#ffb747'
 search_icon_color: '#ec998b'
 search_font_color: '#eee4c4'
 command_font_color: '#eee4c4'
 command_border_color: '#c3eead'
 music_pic_color1: '#f07178'
 music_pic_color2: '#81a8fd'
 usage_color_left: '#beb2ec'
 usage_color_right: '#eee188'
 cut_off_rule_color: '#c3e88d'
 play_music_list_title_color: '#81a8fd'
 play_music_list_border_color: '#ffaaff'
 play_music_list_id_color: '#e0d7ca'
 play_music_list_duration_color: '#a9c34f'
 play_music_list_name_color: '#eee4c4'
 play_music_list_artist_color: '#b2e2e4'
 play_music_list_album_color: '#eee188'
 play_music_list_header_color: '#d15aa7'
 playing_music_border_color: '#81a8fd'
 playing_music_name_color: '#d8ce2e'
 volume_icon_color: '#9998af'
 volume_value_color: '#dcd8da'
 gauge_color: '#cece68'
 gauge_border_color: '#abcc7e'
 gauge_label_color: '#fa4d70'